TFSOLO.BalancingFuncs.push(function(kv)
{
	// Panic Attack
	local key1 = kv.FindKey("prefabs")
	local prefab = key1.FindKey("weapon_trenchgun")
	local attrib = prefab.FindKey("attributes")
	// Only usable by Pyro
	local classuse = prefab.GetKey("used_by_classes", true)
	classuse.RemoveSubKey("engineer")
	classuse.RemoveSubKey("soldier")
	classuse.RemoveSubKey("heavy")
	// Remove existing atrributes 
	attrib.RemoveSubKey("damage penalty")
	attrib.RemoveSubKey("single wep deploy time decreased")
	attrib.RemoveSubKey("mult_spread_scales_consecutive")
	attrib.RemoveSubKey("bullets per shot bonus")
	attrib.RemoveSubKey("fixed_shot_pattern")
	// Add old functionality, +50% reload speed, -33% clip size
	local a1 = attrib.GetKey("panic_attack", true)
	a1.SetString("attribute_class","panic_attack")
	a1.SetInt("value",1)
	local a2 = attrib.GetKey("auto fires full clip hidden", true)
	a2.SetString("attribute_class","auto_fires_full_clip")
	a2.SetInt("value",1)
	local a3 = attrib.GetKey("Reload time decreased", true)
	a3.SetString("attribute_class","mult_reload_time")
	a3.SetFloat("value",0.5)
	local a4 = attrib.GetKey("fire rate bonus", true)
	a4.SetString("attribute_class","mult_postfiredelay")
	a4.SetFloat("value",0.7)
	local a5 = attrib.GetKey("clip size penalty", true)
	a5.SetString("attribute_class","mult_clipsize")
	a5.SetFloat("value",0.66)
})